{{- if .Values.ingress.enabled -}}

---
apiVersion: {{ .Values.ingress.apiVersion }}
kind: Ingress
metadata:
  name: {{ include "jxpipelines.fullname" . }}
  labels:
    {{- include "jxpipelines.labels" . | nindent 4 }}
    {{- with .Values.ingress.labels }}
      {{- tpl (toYaml .) $ | trim | nindent 4 }}
    {{- end }}
  {{- if or .Values.ingress.annotations .Values.ingress.class }}
  annotations:
    {{- with .Values.ingress.class }}
    kubernetes.io/ingress.class: {{ . }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
      {{- tpl (toYaml .) $ | trim | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  rules:
{{- if eq .Values.ingress.apiVersion "networking.k8s.io/v1beta1" }}
  {{- range .Values.ingress.hosts }}
  - host: {{ tpl . $ }}
    http:
      paths:
      - backend:
          serviceName: {{ include "jxpipelines.fullname" $ }}
          servicePort: http
  {{- end }}
{{- else }}
  {{- $pathType := .Values.ingress.pathType | default "ImplementationSpecific" -}}
  {{- $path  := .Values.ingress.path -}}
  {{- range .Values.ingress.hosts }}
  - host: {{ tpl . $ }}
    http:
      paths:
      - pathType: {{ $pathType }}
        backend:
          service:
            name: {{ include "jxpipelines.fullname" $ }}
            port:
              name: http
        {{- if eq $pathType "Prefix" }}
        path: {{ $path | default "/" }}
        {{- end }}
  {{- end }}
{{- end }}

  {{- if .Values.ingress.tls.enabled }}
  tls:
  {{- range $name, $secret := .Values.ingress.tls.secrets }}
  {{- if and $secret.b64encodedCertificate $secret.b64encodedCertificateKey }}
  - secretName: {{ include "jxpipelines.fullname" $ }}-tls-{{ $name }}
  {{- else }}
  - secretName: {{ $name }}
  {{- end }}
    hosts:
    {{- if $secret.hosts }}
    {{- range $secret.hosts }}
    - {{ . }}
    {{- end }}
    {{- else }}
    {{- range $.Values.ingress.hosts }}
    - {{ . }}
    {{- end }}
    {{- end }}
  {{- end }}
  {{- end }}

{{- if .Values.ingress.basicAuth.enabled }}
---
apiVersion: v1
data:
  auth: {{ .Values.ingress.basicAuth.authData | quote }}
kind: Secret
metadata:
  name: jx-pipelines-visualizer-basic-auth
type: Opaque
{{- end -}}

{{- if .Values.ingress.tls.enabled -}}
{{- range $name, $secret := .Values.ingress.tls.secrets -}}
{{- if and $secret.b64encodedCertificate $secret.b64encodedCertificateKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jxpipelines.fullname" $ }}-tls-{{ $name }}
  labels: {{- include "jxpipelines.labels" $ | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $secret.b64encodedCertificate | quote }}
  tls.key: {{ $secret.b64encodedCertificateKey | quote }}
{{- end -}}
{{- end -}}
{{- end -}}

{{- end -}}
