{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-01T15:39:13Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: noreply@github.com
      name: GitHub
    message: 'chore: add file for changelog'
    sha: 1048cfebc14d2207608a7ef9cc68fba26e798b5e
  - author:
      email: v.behar@free.fr
      name: Vincent Behar
    branch: master
    committer:
      email: v.behar@free.fr
      name: Vincent Behar
    issueIds:
    - "91"
    message: |
      fix: support repos with underscore

      fixes #91
    sha: 631586f6cb660be5fff1765c78f517db7c3209a0
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: james.strachan@gmail.com
      name: James Strachan
    message: |
      chore: upgrade pipelines
    sha: 739d49c80d88f0ebe97c4b49ae71bd58ec2157bd
  gitHttpUrl: https://github.com/jenkins-x/jx-pipelines-visualizer
  gitOwner: jenkins-x
  gitRepository: jx-pipelines-visualizer
  issues:
  - body: "All other repos work, and the logs are in fact in s3. `jx get build logs` also retreives them successfully.\r\n\r\n![image](https://user-images.githubusercontent.com/474827/106169988-fd08d780-615d-11eb-90f7-5b2b3bf07533.png)\r\n\r\n![image](https://user-images.githubusercontent.com/474827/106170098-1f9af080-615e-11eb-85ea-637648c31d77.png)\r\n\r\n"
    creationTimestamp: "2021-01-28T16:43:22Z"
    id: "91"
    state: closed
    title: 'Error: Archived logs not found in the long term storage for repos with underscores in name '
    url: https://github.com/jenkins-x/jx-pipelines-visualizer/issues/91
  name: '{{ .Chart.Name }}'
  version: 1.1.4
status: {}
 
{{- end }}
