{{- if and (.Capabilities.APIVersions.Has "jenkins.io/v1/Release") (hasKey .Values.jx "releaseCRD") (.Values.jx.releaseCRD)}}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-04-06T08:04:14Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: james.strachan@gmail.com
      name: James Strachan
    branch: master
    committer:
      email: noreply@github.com
      name: GitHub
    message: |-
      fix: release pipeline

      to avoid the generated Release CRD template breaking lint
    sha: e44b54241a0f0b0e107e3df92e0306c00d4581b0
  - author:
      email: v.behar@free.fr
      name: Vincent Behar
    branch: master
    committer:
      email: v.behar@free.fr
      name: Vincent Behar
    message: |
      fix: only display trace link if there is a trace
    sha: 27d393a30c81dae543017c2686771ff3fe51fbd9
  - author:
      email: v.behar@free.fr
      name: Vincent Behar
    branch: master
    committer:
      email: v.behar@free.fr
      name: Vincent Behar
    message: |
      feat: open pipeline trace URL

      use grafana tempo to open the pipeline trace - if available
    sha: 6558eb1b02d39b59b24df27a18d792a69aa6f7cc
  - author:
      email: v.behar@free.fr
      name: Vincent Behar
    branch: master
    committer:
      email: v.behar@free.fr
      name: Vincent Behar
    message: |
      feat: support archived pipelineruns

      load pipelineruns from the long-term storage, so that we don't answer with 404 once the pipelineruns have been garbage-collected from the cluster
      see https://github.com/jenkins-x-plugins/jx-build-controller/issues/13
      and https://github.com/jenkins-x-plugins/jx-build-controller/pull/27
    sha: 316cd9075f8afa695d23ff5d4c20ef634e869ee6
  gitHttpUrl: https://github.com/jenkins-x/jx-pipelines-visualizer
  gitOwner: jenkins-x
  gitRepository: jx-pipelines-visualizer
  name: '{{ .Chart.Name }}'
  version: 1.3.0
status: {}
 
{{- end }}
